/opt/DownloaderEnv/bin/pip3 install amqp==1.4.9
/opt/DownloaderEnv/bin/pip3 install anyjson==0.3.3
/opt/DownloaderEnv/bin/pip3 install asgiref==3.2.2
/opt/DownloaderEnv/bin/pip3 install async-timeout==3.0.1
/opt/DownloaderEnv/bin/pip3 install attrs==19.3.0
/opt/DownloaderEnv/bin/pip3 install autobahn==19.10.1
/opt/DownloaderEnv/bin/pip3 install Automat==0.8.0
/opt/DownloaderEnv/bin/pip3 install billiard==3.3.0.23
/opt/DownloaderEnv/bin/pip3 install celery==3.1.19
/opt/DownloaderEnv/bin/pip3 install certifi==2019.9.11
/opt/DownloaderEnv/bin/pip3 install cffi==1.13.0
/opt/DownloaderEnv/bin/pip3 install channels==2.3.0
/opt/DownloaderEnv/bin/pip3 install chardet==3.0.4
/opt/DownloaderEnv/bin/pip3 install constantly==15.1.0
/opt/DownloaderEnv/bin/pip3 install cryptography==2.8
/opt/DownloaderEnv/bin/pip3 install daphne==2.3.0
/opt/DownloaderEnv/bin/pip3 install Django==1.11.23
/opt/DownloaderEnv/bin/pip3 install django-redis==4.4.3
/opt/DownloaderEnv/bin/pip3 install djangorestframework==3.9.4
/opt/DownloaderEnv/bin/pip3 install djangorestframework-jwt==1.11.0
/opt/DownloaderEnv/bin/pip3 install hyperlink==19.0.0
/opt/DownloaderEnv/bin/pip3 install idna==2.8
/opt/DownloaderEnv/bin/pip3 install incremental==17.5.0
/opt/DownloaderEnv/bin/pip3 install kombu==3.0.37
/opt/DownloaderEnv/bin/pip3 install pycparser==2.19
/opt/DownloaderEnv/bin/pip3 install PyHamcrest==1.9.0
/opt/DownloaderEnv/bin/pip3 install PyJWT==1.7.1
/opt/DownloaderEnv/bin/pip3 install pyspeedtest==1.2.7
/opt/DownloaderEnv/bin/pip3 install pytz==2019.3
/opt/DownloaderEnv/bin/pip3 install redis==2.10.5
/opt/DownloaderEnv/bin/pip3 install requests==2.22.0
/opt/DownloaderEnv/bin/pip3 install six==1.12.0
/opt/DownloaderEnv/bin/pip3 install Twisted==19.7.0
/opt/DownloaderEnv/bin/pip3 install txaio==18.8.1
/opt/DownloaderEnv/bin/pip3 install urllib3==1.25.6
/opt/DownloaderEnv/bin/pip3 install zope.interface==4.6.0
